server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: clients-ms
          uri: http://clients-ms:8003
          predicates:
            - Path=/api/clients/**
        - id: tracking-ms
          uri: http://tracking-ms:8003
          predicates:
            - Path=/api/tracking/**
        - id: order-ms
          uri: http://order-ms:8003
          predicates:
            - Path=/api/orders/**
        - id: auth-ms
          uri: http://auth-ms:9000
          predicates:
            - Path=/api/auth/**

  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
      org.springframework.web.reactive: DEBUG
      reactor.netty.http.client: DEBUG
