server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: c-app-products
          uri: http://c-app-products:8003
          predicates:
            - Path=/api/products/**
        - id: c-app-categories
          uri: http://c-app-categories:8003
          predicates:
            - Path=/api/categories/**

  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
      org.springframework.web.reactive: DEBUG
      reactor.netty.http.client: DEBUG
